version: '2.1'

services:
  rabbitmq:
    build: rabbitmq/.
    ports:
      - '15672:15672'
      - '5672:5672'
      - '5671:5671'
    environment:
      RABBITMQ_DEFAULT_PASS: rabbitPass
      RABBITMQ_DEFAULT_USER: rabbitUser
      RABBITMQ_DEFAULT_VHOST: vhost
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    image: 'postgres'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgresPassword'
    volumes:
      - 'postgres:/var/lib/postgresql/data'


  job_api:
    build: ./job_api
    ports:
      - '3000:3000'
    command: bash -c "rm -rf ./tmp/pids && rake db:create && rake db:migrate && rake db:seed && rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      AMQP_ADDRESS: 'amqp://rabbitUser:rabbitPass@rabbitmq:5672/vhost'
      DATABASE_USERNAME: 'postgres'
      DATABASE_PASSWORD: 'postgresPassword'
      DATABASE_HOST: 'postgres'
      DATABASE_PORT: 5432
    volumes:
      - ./job_api/:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5


  sneakers_job:
    build: ./job_api
    command: bash -c "WORKERS=JobImportWorker rake sneakers:run"
    depends_on:
      job_api:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    links:
      - postgres
    environment:
      AMQP_ADDRESS: 'amqp://rabbitUser:rabbitPass@rabbitmq:5672/vhost'
      DATABASE_USERNAME: 'postgres'
      DATABASE_PASSWORD: 'postgresPassword'
      DATABASE_HOST: 'postgres'
      DATABASE_PORT: 5432
    volumes:
      - ./job_api/:/sneakers_job


  job_queue:
    build: ./job_queue
    command: bash -c "sleep 10 && ./start.sh"
    depends_on:
      job_api:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      sneakers_job:
        condition: service_started
    environment:
      AMQP_ADDRESS: 'amqp://rabbitUser:rabbitPass@rabbitmq:5672/vhost'
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
    volumes:
      - ./job_queue/:/job_queue


volumes:
  postgres:
  rabbitmq:
  # job_api:
  # job_queue:
  # sneakers_job:
