version: '2.1'

services:
  rabbitmq:
    build: rabbitmq/.
    ports:
      - '15672:15672'
      - '5672:5672'
      - '5671:5671'
    environment:
      RABBITMQ_DEFAULT_PASS: rabbitPass
      RABBITMQ_DEFAULT_USER: rabbitUser
      RABBITMQ_DEFAULT_VHOST: vhost
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    image: 'postgres'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgresPassword'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  job_api:
    build: ./job_api
    ports:
      - '3000:3000'
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started
    environment:
      PORT: 3000
      AMQP_ADDRESS: 'amqp://rabbitUser:rabbitPass@rabbitmq:5672/vhost'
      DATABASE_USERNAME: 'postgres'
      DATABASE_PASSWORD: 'postgresPassword'
      DATABASE_HOST: 'postgres'
      DATABASE_PORT: 5432
    volumes:
      - ./job_api/:/app

  job_queue:
    build: ./job_queue
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      AMQP_ADDRESS: 'amqp://rabbitUser:rabbitPass@rabbitmq:5672/vhost'
    volumes:
      - ./job_queue/:/app

volumes:
  postgres:
  rabbitmq:
